### PR TITLE
Update symfony-cli.lua

### PR DESCRIPTION
**Pull request by BahmanMD**
@fabpot Optimize `symfony-cli.lua` code

### CODE REVIEW

**Comment by fabpot** [comment]
This file is auto-generated by goreleaser (https://goreleaser.com/customization/gofish/).
Code is here: https://github.com/goreleaser/goreleaser/blob/b28a28efb60b3c869bb26e535eb01c9350fe0a7c/internal/pipe/gofish/gofish.go

**Comment by BahmanMD** [comment]
One of the problems with the code was the lack of 386 versions of Linux and Windows, and with these changes it is only necessary to update the code to only 7 lines.

**Comment by BahmanMD** [comment]
So if you think there is no need for Linux-386 and Windows-386 and you can easily update this repository using goreleaser, do not consider this PR and close it :wink:

**Comment by fabpot** [comment]
Let's this repo be updated automatically.

**Pull request closed without merging**
